### ISSUE TITLE
`#[debug_handler]` could suggest `Deserialize` for `Json`

### ISSUE THREAD

**Issue by FSMaxB** [tokio-rs/axum#1738]
- [x] I have looked for existing issues (including closed) about this

### Motivation

While trying to teach someone axum I suggested the use of the `#[debug_handler]` macro in order to find out why their handler wasn't working. The error message did not however provide enough information for them to figure out the issue on their own, so I had to step in and explain what was wrong.

Following scenario:
```rust
struct NotDeserialize;

#[debug_handler]
async fn handler(_: Json<NotDeserialize>) -> impl IntoResponse {
	StatusCode::OK
}
```

The error message was:
```
error[E0277]: the trait bound `Json<NotDeserialize>: FromRequest<(), Body, _>` is not satisfied
  --> src/main.rs:20:21
   |
20 | async fn handler(_: Json<NotDeserialize>) -> impl IntoResponse {
   |                     ^^^^ the trait `FromRequest<(), Body, _>` is not implemented for `Json<NotDeserialize>`
   |
   = help: the trait `FromRequest<S, B>` is implemented for `Json<T>`
note: required by a bound in `__axum_macros_check_handler_0_from_request_check`
  --> src/main.rs:20:21
   |
20 | async fn handler(_: Json<NotDeserialize>) -> impl IntoResponse {
   |                     ^^^^ required by this bound in `__axum_macros_check_handler_0_from_request_check`
```

### Proposal

It would be great if it didn't just tell you that `FromRequest` isn't implemented but also that this is the case because of a missing implementation of `Deserialize`.

Not sure how feasible this is, given that I haven't really looked at how `debug_handler` is actually implemented so far. But wanted to share this because a new users first impression is often valuable for UX.

**Comment by davidpdrsn** [comment]
Thats a regression I'm surprised we missed actually. Thought we had a test for that but oh well.

On 0.5 the error is

```
error[E0277]: the trait bound `for<'de> NotDeserialize: serde::de::Deserialize<'de>` is not satisfied
  --> src/main.rs:19:21
   |
19 | async fn handler(_: Json<NotDeserialize>) {}
   |                     ^^^^ the trait `for<'de> serde::de::Deserialize<'de>` is not implemented for `NotDeserialize`
   |
```

So something with the `FromRequest`/`FromRequestParts` split in 0.6 broke that.

**Comment by jplatte** [comment]
Fixed by #1797?

**Comment by davidpdrsn** [comment]
I don't think so. It still won't tell you about a missing `Deserialize` implementation, even if `Json` is the last argument.
